export const motivationalPhrases = [
    // --- Frases Originales ---
    "Cada kilómetro cuenta para ser una leyenda.",
    "Tu motor ruge por más XP. ¡A rodar!",
    "La próxima carga podría ser la ganadora.",
    "Sigue sumando puntos, estás a nada del siguiente nivel.",
    "El asfalto te llama, ¡ve por tus puntos!",
    "Más que gasolina, cargas gloria.",
    "Demuestra quién es el rey del camino.",
    "Prepárate para tu próximo gran premio.",
    "Los verdaderos pilotos nunca dejan de sumar.",
    "Acelera hacia tus próximas recompensas.",
    "Tu viaje apenas comienza, ¡sigue sumando!",
    "El tanque lleno y los puntos al máximo.",
    "Eres el dueño de la carretera y de las recompensas.",
    "Cada gota cuenta, cada punto te acerca a tu premio.",
    "Sube de nivel a la velocidad de la luz.",
    "No es solo llegar, es disfrutar el viaje y ganar.",
    "Las mejores rutas siempre traen grandes recompensas.",
    "Pon primera y arranca hacia el siguiente nivel.",
    "Tu lealtad es nuestro motor. ¡Gracias por rodar con nosotros!",
    "Conduce seguro, suma rápido y canjea en grande.",
    "El mapa dice que estás muy cerca de un nuevo logro.",
    "Siente la adrenalina de subir de nivel.",
    "Pisa el acelerador de tus beneficios.",
    "Un buen piloto siempre sabe dónde cargar para ganar.",
    "Tu próximo destino: ¡Nuevas recompensas!",
    "La ruta al éxito está pavimentada con tus puntos.",
    "Llena el tanque, llena tu cuenta de beneficios.",
    "Haz que cada parada en pits valga la pena.",
    "Velocidad, precisión y muchos puntos a tu favor.",
    "Eres imparable. ¡Sigue coleccionando victorias!",
    
    // --- Nuevas Frases ---
    "Tu lealtad tiene premio. ¡Sigue acelerando!",
    "El camino al éxito está lleno de paradas inteligentes.",
    "Carga tras carga, te acercas a la gran meta.",
    "Un buen viaje siempre termina con una excelente recompensa.",
    "Tu tanque no es lo único que se llena el día de hoy.",
    "Mantén el ritmo constante, las recompensas te esperan.",
    "Piloto estrella en ruta, premio asegurado.",
    "Haz de cada trayecto una oportunidad para ganar más.",
    "La carretera es toda tuya, los beneficios también.",
    "No hay límites de velocidad para lo que puedes alcanzar aquí.",
    "Suma kilómetros en el asfalto, multiplica tus puntos en la app.",
    "Un auto impecable y un conductor siempre premiado.",
    "Tu motor te lo agradece, nosotros te lo premiamos.",
    "Siente el verdadero poder de ser parte del Club Pilotos.",
    "La excelencia al volante siempre trae grandes beneficios.",
    "Rumbo a tu próximo nivel, sin pisar los frenos.",
    "Deja tu huella en el camino y en tu cuenta de puntos.",
    "Disfruta el recorrido, nosotros nos encargamos de los premios.",
    "Cada parada a cargar es un avance hacia la cima.",
    "Acelera a fondo tu camino hacia beneficios totalmente exclusivos."
];